# Generated by Django 4.1 on 2023-04-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0001_initial"),
        ("Account", "0002_account_relate_department_account_relate_hospital_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="relate_hospital",),
        migrations.AddField(
            model_name="account",
            name="relate_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Hospital.hospital",
                verbose_name="所属医院",
            ),
        ),
    ]
