# Generated by Django 4.1 on 2023-04-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0001_initial"),
        ("Account", "0003_remove_account_relate_hospital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="res_hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="head",
                to="Hospital.hospital",
                verbose_name="所管理的医院",
            ),
        ),
    ]
