# Generated by Django 4.1 on 2023-04-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0005_rename_relate_department_account_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="hospital",),
        migrations.RemoveField(model_name="account", name="res_hospital",),
        migrations.AddField(
            model_name="account",
            name="age",
            field=models.IntegerField(default=0, verbose_name="年龄"),
        ),
        migrations.AddField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[("f", "female"), ("m", "male"), ("s", "secret")],
                default="s",
                max_length=1,
                verbose_name="性别",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="major",
            field=models.TextField(default="", verbose_name="专业擅长"),
        ),
        migrations.AddField(
            model_name="account",
            name="positions",
            field=models.CharField(blank=True, max_length=100, verbose_name="职位"),
        ),
    ]
