# Generated by Django 4.1 on 2023-04-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0002_delete_hospital"),
        (
            "Account",
            "0006_remove_account_hospital_remove_account_res_hospital_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="department",
            field=models.ManyToManyField(
                blank=True,
                related_name="doctor",
                to="Hospital.department",
                verbose_name="所属科室",
            ),
        ),
    ]
