# Generated by Django 4.1 on 2023-04-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0008_diagnosticrecords"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diagnosticrecords", old_name="patience", new_name="patient",
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[("p", "patient"), ("d", "Doctor")],
                default="p",
                max_length=1,
                verbose_name="角色",
            ),
        ),
    ]
