# Generated by Django 4.1 on 2023-04-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0009_rename_patience_diagnosticrecords_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticrecords",
            name="diagnostic_time",
            field=models.DateTimeField(verbose_name="就诊时间"),
        ),
    ]
