# Generated by Django 4.1 on 2023-05-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0015_alter_diagnosticrecords_options_alter_account_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("p", "patient"),
                    ("d", "Doctor"),
                    ("a", "administrator"),
                    ("g", "guest"),
                ],
                default="p",
                max_length=1,
                verbose_name="角色",
            ),
        ),
    ]
