# Generated by Django 4.1 on 2023-05-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0017_conversion_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="close",
            field=models.BooleanField(default=False, verbose_name="是否关闭"),
        ),
    ]
