# Generated by Django 4.1 on 2023-05-13 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0018_conversion_close"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversion",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 5, 13, 13, 29, 48, 285242, tzinfo=datetime.timezone.utc
                ),
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
    ]
