# Generated by Django 4.1 on 2023-04-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "Account",
            "0006_remove_account_hospital_remove_account_res_hospital_and_more",
        ),
        ("Hospital", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Hospital",),
    ]
