# Generated by Django 4.1 on 2023-05-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Hospital", "0002_delete_hospital"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department", options={"verbose_name": "科室"},
        ),
    ]
